[project]
# Supabase project configuration
project_id = "your-project-id"
name = "gurbetci"

[api]
# API configuration
enabled = true
port = 54321

[db]
# Database configuration
port = 54322
shadow_port = 54323

[studio]
# Studio configuration
port = 54324

[auth]
# Auth configuration
enabled = true
image = "supabase/gotrue:v2.99.0"
site_url = "https://gurbetci.com"
additional_redirect_urls = ["gurbetci://auth/verify", "gurbetci://auth/reset-password"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = true
enable_sms_confirmations = true

[auth.email]
# Email configuration
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
template = "confirmation"
secure_email_change_enabled = true
secure_password_change_enabled = true

[auth.sms]
# SMS configuration
enable_signup = true
enable_confirmations = true
template = "confirmation"

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""

[functions]
# Edge Functions configuration
enabled = true
verify_jwt = true

[storage]
# Storage configuration
enabled = true
image = "supabase/storage-api:v0.40.4"
file_size_limit = 52428800

[edge_runtime]
# Edge Runtime configuration
enabled = true
image = "supabase/edge-runtime:v1.22.4" 